### ISSUE TITLE
Sorry, can you share the pre-trained model?

### ISSUE THREAD

**Issue by Singerone** [shendu0321/IncepFormer#3]
Hello, when I downloaded the pre-trained model through the link, I found that it must need to review the application to access it. I wonder if it is convenient for you to approve my application. And In order to make it easier for you to find my application,my account number is qiaoxiaoqiao08@gmail.com.

Looking forward to your reply,thank you very much!

**Comment by shendu0321** [comment]
I have updated the url, now could download sucessfully.

**Comment by Singerone** [comment]
> I have updated the url, now could download sucessfully.

thank you very much!
